### ISSUE TITLE
How to deploy to a static site?

### ISSUE THREAD

**Issue by GilbertMizrahi** [liqvidjs/liqvid#21]
If I use create-react-app I use npm build, but in this case, how do I do it?
If I don't need to record audio, do I still need install Express?

**Comment by ysulyma** [comment]
No, you don't need to install Express.

I'm working on a `liqvid build` command. For now, upload `bundle.js`, `index.html`, and `style.css` (+ any other static files) to wherever you want on your server. Then embed it from an iframe like so:

```html
<div class="video-container">
  <div class="aspect-ratio" style="padding-bottom: 62.5%">
    <iframe allowfullscreen src="./my-video/"></iframe>
  </div>
</div>
```
with CSS
```css
.video-container {
  width: 100%;
}

.aspect-ratio {
  position: relative;
}

.aspect-ratio > iframe {
  position: absolute;
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
}
```

If you don't need to support old versions of iOS (< 15), you can make this a lot simpler:
```html
<iframe allowfullscreen src="./my-video/"></iframe>
```
```css
iframe {
  aspect-ratio: 16 / 10;
}
```

I'd love to see what you made!
